services:
  - type: web
    name: maxwifiapp
    runtime: docker
    plan: free
    region: oregon
    repo: https://github.com/cruzayala/maxwifiapp
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7400
      - key: DATABASE_URL
        value: file:/tmp/data.db
      - key: WISPHUB_API_KEY
        sync: false
      - key: ACCESS_PIN
        sync: false
      - key: MIKROTIK_HOST
        sync: false
      - key: MIKROTIK_USER
        sync: false
      - key: MIKROTIK_PASS
        sync: false
      - key: MIKROTIK_PORT
        sync: false
