package com.ispmax.mobile

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Rule
import org.junit.rules.ExternalResource
import org.junit.rules.RuleChain
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

@RunWith(AndroidJUnit4::class)
class MobileFlowTest {
    val compose = createAndroidComposeRule<MainActivity>()
    @get:Rule val rules: RuleChain = RuleChain.outerRule(object : ExternalResource() {
        override fun before() { com.ispmax.mobile.data.SessionStore(InstrumentationRegistry.getInstrumentation().targetContext).clear() }
    }).around(compose)
    private fun visible(text: String, substring: Boolean = false) {
        try {
            compose.waitUntil(30000) { runCatching { compose.onAllNodesWithText(text, substring = substring).fetchSemanticsNodes().isNotEmpty() }.getOrDefault(false) }
        } catch (error: ComposeTimeoutException) {
            val rootCount = runCatching { compose.onAllNodes(isRoot(), useUnmergedTree = true).fetchSemanticsNodes().size }.getOrDefault(0)
            throw AssertionError("No aparecio '$text' despues de 30 s ($rootCount raices Compose activas).", error)
        }
    }
    private fun shot(name: String) {
        compose.waitForIdle()
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        instrumentation.waitForIdleSync()
        android.os.SystemClock.sleep(500)
        val directory = File(instrumentation.targetContext.getExternalFilesDir(null), "qa").apply { mkdirs() }
        val capture = runCatching { compose.onAllNodes(isRoot()).onLast().captureToImage().asAndroidBitmap() }
        capture.getOrNull()?.let { bitmap ->
            File(directory, "$name.png").outputStream().use { bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG, 100, it) }
            bitmap.recycle()
        }
        if (capture.isFailure) println("CAPTURE_NOT_AVAILABLE $name: verify with ADB screenshot; functional assertions continue")
        if (InstrumentationRegistry.getArguments().getString("pauseEquipmentShots") == "true" && name in listOf("13-inventario", "14-equipo-cliente", "15-historial-equipo")) android.os.SystemClock.sleep(15000)
    }
    private fun signInAdmin() {
        visible("Iniciar sesion")
        compose.onNodeWithText("Servidor QA", useUnmergedTree = true).performClick()
        compose.onNodeWithText("URL de ISP Max").performTextReplacement("http://127.0.0.1:7415")
        compose.onNodeWithText("Usuario").performTextInput("qa-admin")
        compose.onNodeWithText("Contrasena").performTextInput("qa-only-12345")
        compose.onNodeWithText("Iniciar sesion").performClick()
        visible("Resumen operativo")
    }
    @Test fun invoicePaymentIsVerifiedAndRecoveredWithoutDuplicate() {
        signInAdmin()
        compose.onNodeWithContentDescription("Cobros", useUnmergedTree = true).performClick()
        compose.onNodeWithText("Facturas", substring = false).performClick()
        visible("#9002", substring = true)
        compose.onNodeWithText("#9002", substring = true).performClick()
        visible("Registrar o consultar pago")
        compose.onNodeWithText("Registrar o consultar pago").performClick()
        visible("Importe recibido")
        compose.onNodeWithText("Importe recibido").performTextReplacement("40,50")
        compose.onNodeWithText("Forma de pago").performClick()
        visible("Efectivo QA")
        compose.onNodeWithText("Efectivo QA").performClick()
        shot("22-pago-formulario")
        compose.onNodeWithText("Revisar pago").performScrollTo().performClick()
        visible("Confirmar y enviar")
        compose.onNodeWithText("Confirmar y enviar").performClick()
        visible("Pago confirmado")
        shot("23-pago-confirmado")
        compose.activityRule.scenario.recreate()
        visible("Pago confirmado")
        compose.onNodeWithText("Importes verificados y recibo guardado").assertExists()
        shot("24-pago-recuperado")
        compose.onNodeWithContentDescription("Cerrar pago").performClick()
    }
    @Test fun clientRecordPromiseDraftHistoryAndInvoiceFilters() {
        signInAdmin()
        compose.onNodeWithContentDescription("Clientes", useUnmergedTree = true).performClick()
        visible("Ana Torres")
        compose.onNodeWithText("Ana Torres").performClick()
        visible("Editar expediente local")
        compose.onNodeWithText("Editar expediente local").performClick()
        visible("Nombre local")
        compose.onNodeWithText("Nombre local", substring = false).performTextInput("Ana local Android QA")
        compose.onNodeWithText("Telefono local", substring = false).performTextInput("8095550099")
        compose.onNodeWithContentDescription("Cerrar editor de expediente").performClick()
        compose.onNodeWithText("Editar expediente local").performClick()
        visible("Ana local Android QA")
        compose.activityRule.scenario.recreate()
        visible("Ana local Android QA")
        compose.onNodeWithText("Guardar expediente").performClick()
        visible("Ana local Android QA")
        shot("16-expediente-local")
        compose.onNodeWithText("Historial", substring = false).performScrollTo().performClick()
        visible("Expediente actualizado")
        shot("17-historial-cliente")
        compose.onNodeWithText("Datos", substring = false).performScrollTo().performClick()
        visible("Editar expediente local")
        compose.onNodeWithText("Editar expediente local").performClick()
        visible("Nombre local")
        compose.onNodeWithText("Nombre local", substring = false).performTextClearance()
        compose.onNodeWithText("Telefono local", substring = false).performTextClearance()
        compose.onNodeWithText("Guardar expediente").performClick()
        visible("Ana Torres")
        compose.onNodeWithText("Promesas del cliente").performScrollTo().performClick()
        visible("Sin promesas para estos filtros")
        compose.onNodeWithContentDescription("Nueva promesa").performClick()
        visible("Importe comprometido")
        compose.onNodeWithText("Importe comprometido").performTextInput("450,50")
        compose.onNodeWithText("Notas de seguimiento").performTextInput("Promesa aislada QA")
        compose.onNodeWithContentDescription("Cerrar editor de expediente").performClick()
        visible("Compromisos de pago")
        compose.onNodeWithContentDescription("Nueva promesa").performClick()
        visible("450,50")
        compose.onNodeWithText("Guardar promesa").performClick()
        visible("1 compromisos")
        shot("18-promesa-creada")
        compose.onNodeWithContentDescription("Editar promesa").performClick()
        visible("Importe comprometido")
        compose.onNodeWithTag("promise-status-paid").performScrollTo().performClick()
        compose.onNodeWithText("Guardar promesa").performClick()
        visible("Actualizar seguimiento")
        compose.onNodeWithText("Confirmar estado").performClick()
        visible("1 compromisos")
        visible("Cumplida", substring = true)
        shot("19-promesa-cumplida")
        compose.onNodeWithContentDescription("Cerrar promesas del cliente").performClick()
        compose.onNodeWithContentDescription("Cobros", useUnmergedTree = true).performClick()
        compose.onNodeWithText("Facturas", substring = false).performClick()
        visible("2 resultados")
        visible("RD$ 2,100.00")
        compose.onNodeWithText("Mas filtros").performClick()
        visible("Zona exacta")
        compose.onNodeWithText("Zona exacta").performTextInput("Sin zona QA")
        compose.onNodeWithText("Aplicar filtros").performClick()
        visible("0 resultados")
        compose.onNodeWithContentDescription("Limpiar filtros avanzados").performClick()
        visible("2 resultados")
        shot("20-facturas-kpi")
        compose.onNodeWithContentDescription("Volver").performClick()
        compose.onNodeWithText("Reporte de facturacion").performScrollTo().performClick()
        visible("Facturacion por emision")
        visible("3 meses")
        compose.onNodeWithText("3 meses").performClick()
        visible("Facturado y cobrado por mes de emision")
        shot("21-reporte-facturacion")
    }
    @Test fun administrationExpenseCreateEditDeleteAndSessionInventory() {
        signInAdmin()
        compose.onNodeWithContentDescription("Mas", useUnmergedTree = true).performClick()
        compose.onNodeWithText("Gastos", substring = false).performScrollTo().performClick()
        visible("No hay gastos para estos filtros")
        compose.onNodeWithContentDescription("Nuevo gasto").performClick()
        visible("Descripcion")
        compose.onNodeWithText("Guardar gasto", substring = false).performClick()
        visible("Escribe una descripcion", substring = true)
        compose.onNodeWithText("Descripcion", substring = false).performTextInput("Transporte QA Android")
        compose.onNodeWithText("Importe", substring = false).performTextInput("125,50")
        compose.onNodeWithContentDescription("Cerrar editor de gasto").performClick()
        compose.onNodeWithContentDescription("Nuevo gasto").performClick()
        visible("Transporte QA Android")
        compose.activityRule.scenario.recreate()
        visible("Transporte QA Android")
        compose.onNodeWithText("Asociar cliente", substring = false).performScrollTo().performClick()
        visible("Ana Torres")
        compose.onNodeWithText("Buscar cliente para gasto").performTextInput("192.0.2.10")
        compose.onNodeWithText("Ana Torres", substring = false).performClick()
        compose.onNodeWithText("Guardar gasto", substring = false).performClick()
        visible("Gastos registrados")
        visible("Transporte QA Android")
        shot("11-gastos")
        compose.onNodeWithText("Transporte QA Android").performClick()
        visible("Editar gasto")
        compose.onNodeWithText("Editar gasto").performClick()
        visible("Descripcion")
        compose.onNodeWithText("Descripcion", substring = false).performTextReplacement("Transporte QA editado")
        compose.onNodeWithText("Guardar gasto", substring = false).performClick()
        visible("Gastos registrados")
        visible("Transporte QA editado")
        compose.onNodeWithText("Transporte QA editado").performClick()
        compose.onNodeWithContentDescription("Eliminar gasto").performClick()
        visible("Se eliminara este gasto", substring = true)
        compose.onNodeWithText("Eliminar", substring = false).performClick()
        visible("No hay gastos para estos filtros")
        compose.onNodeWithContentDescription("Volver").performClick()
        compose.onNodeWithText("Sesiones moviles").performScrollTo().performClick()
        visible("Este dispositivo")
        shot("12-sesiones")
        compose.onNodeWithText("Cerrar esta sesion").performScrollTo().performClick()
        visible("Revocar sesion")
        compose.onNode(hasText("Revocar sesion") and hasClickAction()).performClick()
        visible("Iniciar sesion")
    }
    @Test fun roleMenusDoNotExposeUnrelatedModules() {
        for (role in listOf("tecnico", "cobranza", "viewer")) {
            visible("Iniciar sesion")
            compose.onNodeWithText("Servidor QA", useUnmergedTree = true).performClick()
            compose.onNodeWithText("URL de ISP Max").performTextReplacement("http://127.0.0.1:7415")
            compose.onNodeWithText("Usuario").performTextInput("qa-$role")
            compose.onNodeWithText("Contrasena").performTextInput("qa-only-12345")
            compose.onNodeWithText("Iniciar sesion").performClick()
            visible("Resumen operativo")
            if (role != "tecnico") compose.onNodeWithContentDescription("Red", useUnmergedTree = true).assertDoesNotExist()
            if (role != "cobranza") compose.onNodeWithContentDescription("Cobros", useUnmergedTree = true).assertDoesNotExist()
            compose.onNodeWithContentDescription("Clientes", useUnmergedTree = true).performClick()
            visible("Ana Torres")
            compose.onNodeWithText("Ana Torres").performClick()
            visible("Expediente #301")
            if (role == "cobranza") compose.onNodeWithText("Abrir cartera y facturas").assertExists()
            else compose.onNodeWithText("Abrir cartera y facturas").assertDoesNotExist()
            compose.onNodeWithText("Notas", substring = false).performClick()
            if (role == "viewer") compose.onNodeWithText("Agregar nota").assertDoesNotExist()
            else compose.onNodeWithText("Agregar nota").assertExists()
            compose.onNodeWithContentDescription("Mas", useUnmergedTree = true).performClick()
            compose.onNodeWithText("Gastos", substring = false).assertDoesNotExist()
            compose.onNodeWithText("Inventario", substring = false).assertDoesNotExist()
            compose.onNodeWithText("Nomina", substring = false).assertDoesNotExist()
            shot("rol-$role")
            compose.onNodeWithText("Cerrar sesion").performScrollTo().performClick()
            visible("Iniciar sesion")
        }
    }
    @Test fun loginBrowseClientWalletNoteAndLogout() {
        visible("Iniciar sesion")
        shot("01-login")
        compose.onNodeWithText("Servidor QA", useUnmergedTree = true).performClick()
        compose.onNodeWithText("URL de ISP Max").performTextReplacement("http://127.0.0.1:7415")
        compose.onNodeWithText("Usuario").performTextInput("qa-admin")
        compose.onNodeWithText("Contrasena").performTextInput("qa-only-12345")
        compose.onNodeWithText("Iniciar sesion").performClick()
        visible("Resumen operativo")
        visible("3")
        shot("02-dashboard")
        compose.onNodeWithContentDescription("Clientes", useUnmergedTree = true).performClick()
        visible("Ana Torres")
        shot("03-clientes")
        compose.onNodeWithText("Suspendidos", substring = false).performClick()
        visible("1 resultados")
        compose.onNodeWithText("Luis Rodriguez").assertExists()
        compose.onNodeWithText("Todos", substring = false).performClick()
        visible("3 resultados")
        compose.onAllNodes(hasSetTextAction()).onFirst().performTextInput("cliente-inexistente-qa")
        visible("No hay resultados para esta busqueda")
        compose.onNodeWithContentDescription("Limpiar busqueda").performClick()
        visible("3 resultados")
        compose.onAllNodes(hasSetTextAction()).onFirst().performTextInput("192.0.2.10")
        visible("1 resultados")
        compose.onNodeWithText("Ana Torres").performClick()
        visible("Expediente #301")
        visible("ana-qa")
        compose.activityRule.scenario.recreate()
        visible("Expediente #301")
        compose.onNodeWithContentDescription("Volver").performClick()
        visible("1 resultados")
        compose.onNodeWithText("192.0.2.10", substring = false).assertExists()
        compose.onNodeWithText("Ana Torres").performClick()
        visible("Expediente #301")
        shot("04-expediente")
        compose.onNodeWithText("Servicio", substring = false).performClick()
        visible("Fibra 50M")
        compose.onNodeWithText("Equipos", substring = false).performClick()
        visible("Sin equipos asignados")
        compose.onNodeWithText("Datos", substring = false).performClick()
        compose.onNodeWithText("Abrir cartera y facturas").performClick()
        visible("#9001", substring = true)
        shot("05-cartera")
        compose.onNodeWithText("#9001", substring = true).performClick()
        visible("Ver documento")
        compose.onNodeWithText("Ver documento").performClick()
        visible("Factura #9001")
        compose.waitUntil(30000) { compose.onAllNodes(hasContentDescription("Imprimir o guardar PDF") and isEnabled()).fetchSemanticsNodes().isNotEmpty() }
        shot("05b-documento")
        // Allow an external screenshot when the emulator's accessibility service is occupied.
        val documentPause = InstrumentationRegistry.getArguments().getString("pauseDocumentMs")?.toLongOrNull() ?: 0
        if (documentPause > 0) android.os.SystemClock.sleep(documentPause.coerceAtMost(60000))
        compose.onNodeWithContentDescription("Imprimir o guardar PDF").assertIsDisplayed()
        if (InstrumentationRegistry.getArguments().getString("skipExternalPrint") != "true") {
            compose.onNodeWithContentDescription("Imprimir o guardar PDF").performClick()
            val automation = InstrumentationRegistry.getInstrumentation().uiAutomation
            compose.waitUntil(15000) { automation.rootInActiveWindow?.packageName?.toString() == "com.android.printspooler" }
            automation.performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK)
            visible("Factura #9001")
        } else {
            println("NOT VERIFIED: external Android printing is explicitly excluded on this emulator.")
        }
        compose.onNodeWithContentDescription("Cerrar documento").performClick()
        compose.onNodeWithContentDescription("Cerrar cartera").performClick()
        visible("Notas")
        compose.onNodeWithText("Notas").performClick()
        compose.onNodeWithText("Agregar nota").performClick()
        visible("Nota del cliente")
        compose.onNodeWithText("Nota", substring = false).performTextInput("Nota QA desde Android")
        compose.onNodeWithText("Guardar en servidor").performClick()
        visible("Nota QA desde Android")
        shot("06-nota")
        compose.onNodeWithContentDescription("Cobros", useUnmergedTree = true).performClick()
        shot("06c-cobros-menu")
        compose.onNodeWithText("Facturas", substring = false).performClick()
        visible("2 resultados")
        compose.onNodeWithText("Pagadas", substring = false).performClick()
        visible("1 resultados")
        compose.onNodeWithText("Ana Torres").assertExists()
        compose.onNodeWithText("Pendientes", substring = false).performClick()
        visible("1 resultados")
        visible("Luis Rodriguez")
        shot("06b-facturas-filtradas")
        compose.onNodeWithText("Luis Rodriguez").performClick()
        visible("Ver documento")
        compose.activityRule.scenario.recreate()
        visible("Ver documento")
        compose.onNodeWithText("Cerrar", substring = false).performClick()
        compose.onNodeWithContentDescription("Volver").performClick()
        compose.onNodeWithText("Saldos pendientes").performClick()
        visible("1 resultados")
        compose.onNodeWithText("Luis Rodriguez").assertExists()
        compose.onNodeWithContentDescription("Red", useUnmergedTree = true).performClick()
        shot("06d-red-menu")
        // La OLT usa las rutas web (/olt-api), que el servidor QA movil no monta: basta con que abra.
        compose.onNodeWithText("OLT y ONU", substring = false).performScrollTo().performClick()
        visible("Infraestructura óptica")
        shot("06e-olt-abierto")
        compose.onNodeWithContentDescription("Volver").performClick()
        compose.onNodeWithText("Incidentes NOC", substring = false).performScrollTo().performClick()
        visible("No hay incidencias para estos filtros")
        compose.onNodeWithContentDescription("Volver").performClick()
        compose.onNodeWithText("Configurar ONU", substring = false).performScrollTo().performClick()
        visible("Centro de agentes ONU")
        compose.onNodeWithText("Prueba local desde este", substring = true).performClick()
        visible("Conectar e identificar")
        compose.onNodeWithText("Escritura bloqueada:", substring = true).performScrollTo().assertIsDisplayed()
        shot("09-onu-compatibilidad")
        compose.onNodeWithContentDescription("Mas", useUnmergedTree = true).performClick()
        for ((module, content) in listOf("Planes" to "Fibra 50M", "Tickets" to "Revision de potencia", "Inventario" to "No hay equipos para estos filtros", "Nomina" to "No hay registros de nomina")) {
            compose.onNodeWithText(module, substring = false).performScrollTo().performClick()
            visible(content)
            if (module == "Tickets") {
                compose.onNodeWithText(content, substring = false).performClick()
                visible("Editar o cerrar ticket")
                shot("10-Tickets")
                compose.onNodeWithContentDescription("Cerrar ticket").performClick()
            } else if (module == "Planes") {
                shot("10-Planes")
            }
            val refresh = when (module) {
                "Planes" -> "Actualizar planes"
                "Tickets" -> "Actualizar tickets"
                "Inventario" -> "Actualizar inventario"
                else -> "Actualizar nomina"
            }
            compose.onNodeWithContentDescription(refresh).performClick()
            visible(content)
            compose.onNodeWithContentDescription("Volver").performClick()
        }
        compose.onNodeWithText("Cerrar sesion").performScrollTo().performClick()
        visible("Iniciar sesion")
        compose.activityRule.scenario.recreate()
        visible("Iniciar sesion")
        compose.onNodeWithText("Servidor QA", useUnmergedTree = true).performClick()
        compose.onNodeWithText("http://127.0.0.1:7415").assertExists()
    }

    @Test fun equipmentRegisterDraftAssignFromClientReturnAndDelete() {
        signInAdmin()
        compose.onNodeWithContentDescription("Mas", useUnmergedTree = true).performClick()
        compose.onNodeWithText("Inventario").performScrollTo().performClick()
        visible("No hay equipos para estos filtros")
        compose.onNodeWithContentDescription("Registrar equipo").performClick()
        visible("Guardar equipo")
        compose.onNodeWithText("Guardar equipo").performClick()
        visible("Selecciona el tipo de equipo")
        compose.onNodeWithText("Seleccionar tipo de equipo").performClick()
        visible("ONU de prueba")
        compose.onNodeWithText("ONU de prueba").performClick()
        compose.onNodeWithText("Serial del equipo").performTextInput("ANDROID-EQUIPMENT-QA")
        compose.onNodeWithText("Modelo", substring = false).performScrollTo().performTextInput("Equipo Android QA")
        compose.onNodeWithContentDescription("Cerrar operacion de equipo").performClick()
        compose.onNodeWithContentDescription("Registrar equipo").performClick()
        visible("ANDROID-EQUIPMENT-QA")
        compose.activityRule.scenario.recreate()
        visible("ANDROID-EQUIPMENT-QA")
        compose.onNodeWithText("Guardar equipo").performClick()
        visible("Equipo Android QA")
        shot("13-inventario")
        compose.onNodeWithContentDescription("Clientes", useUnmergedTree = true).performClick()
        visible("Ana Torres")
        compose.onNodeWithText("Ana Torres").performClick()
        compose.onNodeWithText("Equipos", substring = false).performClick()
        compose.onNodeWithText("Gestionar equipos").performClick()
        visible("No hay equipos para estos filtros")
        compose.onNodeWithText("Asignar desde stock").performClick()
        visible("Equipo Android QA")
        compose.onNodeWithText("Equipo Android QA").performClick()
        visible("Asignar a cliente")
        compose.onNodeWithText("Asignar a cliente").performScrollTo().performClick()
        visible("Confirmar asignacion")
        compose.onNodeWithText("Cliente #301").assertExists()
        compose.onNodeWithText("Notas de instalacion").performTextInput("Instalacion Android QA")
        compose.onNodeWithText("Confirmar asignacion").performClick()
        visible("No hay equipos para estos filtros")
        compose.onNodeWithText("Volver a equipos del cliente").performClick()
        visible("Equipo Android QA")
        shot("14-equipo-cliente")
        compose.onNodeWithText("Equipo Android QA").performClick()
        visible("Devolver a stock")
        compose.onNodeWithText("Historial de movimientos").performScrollTo()
        visible("Asignacion", substring = false)
        shot("15-historial-equipo")
        compose.onNodeWithText("Devolver a stock").performScrollTo().performClick()
        visible("Confirmar devolucion")
        compose.onNodeWithText("Confirmar devolucion").performClick()
        visible("No hay equipos para estos filtros")
        compose.onNodeWithContentDescription("Cerrar inventario del cliente").performClick()
        visible("Sin equipos asignados")
        compose.onNodeWithContentDescription("Mas", useUnmergedTree = true).performClick()
        compose.onNodeWithText("Inventario").performScrollTo().performClick()
        visible("Equipo Android QA")
        compose.onNodeWithText("Buscar equipo").performTextInput("SIN-COINCIDENCIA")
        visible("No hay equipos para estos filtros")
        compose.onNodeWithContentDescription("Limpiar equipos").performClick()
        visible("Equipo Android QA")
        compose.onNodeWithText("Equipo Android QA").performClick()
        visible("Editar equipo")
        compose.onNodeWithText("Editar equipo").performScrollTo().performClick()
        visible("Modelo", substring = false)
        compose.onNodeWithText("Modelo", substring = false).performScrollTo().performTextReplacement("Equipo editado QA")
        compose.onNodeWithText("Guardar equipo").performClick()
        visible("Equipo editado QA")
        compose.onNodeWithText("Equipo editado QA").performClick()
        visible("Eliminar equipo")
        compose.onNodeWithText("Eliminar equipo").performScrollTo().performClick()
        visible("Confirmar eliminacion")
        compose.onNodeWithText("Confirmar eliminacion").performClick()
        visible("No hay equipos para estos filtros")
        compose.onNodeWithContentDescription("Mas", useUnmergedTree = true).performClick()
        compose.onNodeWithText("Cerrar sesion").performScrollTo().performClick()
        visible("Iniciar sesion")
    }
}
